name: Front-end tests

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  js-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run front-end tests
        run: npm test
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
      - name: Run end-to-end tests
        run: npm run test:e2e
